### ISSUE TITLE
Where is newest version!

### ISSUE THREAD

**Issue by RubenBroere** [dvdgrwn/ay-ay-captain#33]
ello my name is Ruben (Friend of Dirruk),

Where! Is! NEW VERSIOOn!
I want play game but no release? plz help
tank you

Ruben

**Comment by WantToBeeMe** [comment]
WHAHAHAHA, klootzakk

**Comment by WantToBeeMe** [comment]
gast, haha, stuur anders ook hier een server invite door

**Comment by RubenBroere** [comment]
https://discord.gg/kDk9PZVv

**Comment by WantToBeeMe** [comment]
GAST, whahaha, dat was sarcastisch

**Comment by WantToBeeMe** [comment]
nu niet meer openen
